### ISSUE TITLE
Run time error doing `npm start` in frontend

### ISSUE THREAD

**Issue by Vindexus** [endel/tic-tac-toe#3]
I did `npm install` then `npm start` and get the following error log

``````vindexus:tic-tac-toe$ cd frontend/
vindexus:frontend$ npm install
npm WARN tictactoe-frontend@1.0.0 No repository field.

up to date in 4.925s
vindexus:frontend user$ npm start

> tictactoe-frontend@1.0.0 start /Users/vindexus/personal/tic-tac-toe/frontend
> webpack-dev-server

/Users/vindexus/personal/tic-tac-toe/frontend/node_modules/webpack-cli/bin/config-yargs.js:89
        describe: optionsSchema.definitions.output.properties.path.description,
                                                  ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/vindexus/personal/tic-tac-toe/frontend/node_modules/webpack-cli/bin/config-yargs.js:89:47)
    at Object.<anonymous> (/Users/vindexus/personal/tic-tac-toe/frontend/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tictactoe-frontend@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tictactoe-frontend@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vindexus/.npm/_logs/2018-09-25T23_34_00_922Z-debug.log$```

**Comment by endel** [comment]
Thanks a lot for reporting @Vindexus, this has been fixed by upgrading the `webpack-cli` package. Cheers!
