### ISSUE TITLE
Can't deploy to Heroku

### ISSUE THREAD

**Issue by IanMayo** [endel/tic-tac-toe#4]
I can see from the repo home page that there's a version of this deployed to, and hosted upon Heroku at:
http://tictactoe-colyseus.herokuapp.com/

But, when I try to deploy a tictactoe fork to Heroku, the build fails.   

I guess this app last deployed to Heroku 3 months ago.  Is there a chance that something has changed in Heroku?

````
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 10.x...
       Downloading and installing node 10.15.0...
       Using default npm version: 6.4.1
       
-----> Building dependencies
       Installing node modules (package.json)
       
       > tictactoe-colyseus@1.0.0 install /tmp/build_440857dca46023323bda307c0179e1ac
       > npm install --prefix ./server && npm install --prefix ./frontend && npm run build --prefix ./frontend
       
       
       > colyseus@0.9.26 postinstall /tmp/build_440857dca46023323bda307c0179e1ac/server/node_modules/colyseus
       > npm run -s donate
       
       Love Colyseus? Support its development by becoming a backer:
        > https://www.patreon.com/endel
       added 309 packages from 290 contributors and audited 4632 packages in 6.935s
       found 0 vulnerabilities
       
       
       > colyseus.js@0.9.15 postinstall /tmp/build_440857dca46023323bda307c0179e1ac/frontend/node_modules/colyseus.js
       > npm run -s donate
       
       Love Colyseus? Support its development by becoming a backer:
        > https://www.patreon.com/endel
       added 22 packages from 22 contributors and audited 9291 packages in 4.71s
       found 0 vulnerabilities
       
       
       > tictactoe-frontend@1.0.0 build /tmp/build_440857dca46023323bda307c0179e1ac/frontend
       > webpack
       
       /tmp/build_440857dca46023323bda307c0179e1ac/node_modules/webpack-cli/bin/config-yargs.js:89
       				describe: optionsSchema.definitions.output.properties.path.description,
       				                                           ^
       
       TypeError: Cannot read property 'properties' of undefined
           at module.exports (/tmp/build_440857dca46023323bda307c0179e1ac/node_modules/webpack-cli/bin/config-yargs.js:89:48)
           at /tmp/build_440857dca46023323bda307c0179e1ac/node_modules/webpack-cli/bin/webpack.js:60:27
           at Object.<anonymous> (/tmp/build_440857dca46023323bda307c0179e1ac/node_modules/webpack-cli/bin/webpack.js:515:3)
           at Module._compile (internal/modules/cjs/loader.js:689:30)
           at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
           at Module.load (internal/modules/cjs/loader.js:599:32)
           at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
           at Function.Module._load (internal/modules/cjs/loader.js:530:3)
           at Module.require (internal/modules/cjs/loader.js:637:17)
           at require (internal/modules/cjs/helpers.js:22:18)
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! tictactoe-frontend@1.0.0 build: `webpack`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the tictactoe-frontend@1.0.0 build script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.fEY81/_logs/2019-01-18T13_39_44_035Z-debug.log
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! tictactoe-colyseus@1.0.0 install: `npm install --prefix ./server && npm install --prefix ./frontend && npm run build --prefix ./frontend`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the tictactoe-colyseus@1.0.0 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.fEY81/_logs/2019-01-18T13_39_44_099Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
````

**Comment by IanMayo** [comment]
Got it, @endel  - the webpack-cli needs to be updated (again).  I changed it to 3.2.1 in the top-level and the frontend packages, and it worked.
